### ISSUE TITLE
The problem about the operation of ChatGPT

### ISSUE THREAD

**Issue by jimmy8399** [IvanCampos/discord-ai#1]
Dear Sir,

Here is the user who is interested in ChatGPT. It is a good artificial intelligence chatbot for people to ask a lot of question in their life. It can mostly give an answer that is useful. However, when I “chat” with the chatbot on the website version of ChatGPT, I think that the “coherence thinking” is the problem for this chatbot to solve. 

Here is the example that I chat with the chatbot on DISCORD and LINE today,
I: what day is today?
AI: you need to give me a place before I ask what day today is.
I: Taiwan
AI: Taiwan has a lot of natural resources….$&@.

According to the conversation I chat on DISCORD, it cannot correctly give me what day is today. I expect that the chatbot can answer me what day today is. Unfortunately, it cannot logically answer me.

Thus, to make ChatGPT be more good for people in life. I would like to know whether the problem, coherence thinking, can be solved on the website version of ChatGPT?       Moreover, if you please, you can log in my DISCORD ChatGPT Server to  detect it. Thanks a lot

Sincerely,
jimmy

**Comment by IvanCampos** [comment]
The training data used for the model behind the ChatGPT API is only up to date as of September 2021. Therefore, the current version of ChatGPT cannot answer "what day is today?" as it is not aware of anything after September 2021. 

**Source:** https://platform.openai.com/docs/models/gpt-3-5

**Comment by jimmy8399** [comment]
thanks for reply , but i mean can anyway modify the code to make Chatbot “talk coherently”between last sentence?
