### ISSUE TITLE
The problem about the operation of ChatGPT 

### ISSUE THREAD

**Issue by jimmy8399** [IvanCampos/discord-ai#2]
thanks for reply , but i mean can anyway modify the code to make Chatbot “talk coherently”between last sentence?

_Originally posted by @jimmy8399 in https://github.com/IvanCampos/discord-ai/issues/1#issuecomment-1459540610_

**Comment by IvanCampos** [comment]
Sorry, but this question sounds like a general support question about the OpenAI API and not code in this repo.

Please go through the proper channels as opposed to creating Issues:
- openai dev community: https://community.openai.com/
- openai discord channel: https://discord.com/invite/openai
